org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.19.4
terrablender_version=2.2.0.154
minecraft_version_range=[1.19.4,1.20)
forge_version=45.3.0
forge_version_range=[45,)
loader_version_range=[45,)
mapping_channel=parchment
mapping_version=2023.06.26-1.19.4
mod_id=multiverse
mod_name=Multiverse
mod_license=GPLv3
mod_version=1.19.4-4.3.0
mod_group_id=multiverse
mod_authors=DavidQF555