org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false
minecraft_version=1.21.4
terrablender_version=4.3.0.2
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.67-beta
neo_version_range=[21,)
loader_version_range=[4,)
mod_id=multiverse
mod_name=Multiverse
mod_license=GPLv3
mod_version=4.0.0
mod_group_id=io.github.davidqf555.minecraft.multiverse
mod_authors=DavidQF555
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.01.19